# Copyright (c) 2022 Gemba Advantage
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - id: codecommit-sign
    main: ./cmd/codecommitsign
    binary: codecommit-sign
    ldflags:
      - -s -w
      - -X github.com/gembaadvantage/codecommit-sign/internal/version.version={{.Tag}}
      - -X github.com/gembaadvantage/codecommit-sign/internal/version.gitCommit={{.Commit}}
      - -X github.com/gembaadvantage/codecommit-sign/internal/version.gitBranch=main
      - -X github.com/gembaadvantage/codecommit-sign/internal/version.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - id: codecommit-sign-archive
    format: tar.gz
    name_template: |-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}
    builds:
      - codecommit-sign
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

signs:
  - artifacts: checksum

brews:
  - name: codecommit-sign
    tap:
      owner: gembaadvantage
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/gembaadvantage/codecommit-sign"
    description: "Generate a signed AWS V4 CodeCommit URL directly from an IAM role. No dedicated CodeCommit credentials needed"
    license: MIT
    install: |
      bin.install "codecommit-sign"

      bash_output = Utils.safe_popen_read(bin/"codecommit-sign", "completion", "bash")
      (bash_completion/"codecommit-sign").write bash_output

      zsh_output = Utils.safe_popen_read(bin/"codecommit-sign", "completion", "zsh")
      (zsh_completion/"_codecommit-sign").write zsh_output

      fish_output = Utils.safe_popen_read(bin/"codecommit-sign", "completion", "fish")
      (fish_completion/"codecommit-sign.fish").write fish_output

      man1.install "manpages/codecommit-sign.1.gz"
    test: |
      installed_version = shell_output("#{bin}/codecommit-sign version --short 2>&1")
      assert_match "v#{version}", installed_version

scoop:
  bucket:
    owner: gembaadvantage
    name: scoops
  homepage: "https://github.com/gembaadvantage/codecommit-sign"
  description: "Generate a signed AWS V4 CodeCommit URL directly from an IAM role. No dedicated CodeCommit credentials needed"
  license: MIT

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/gembaadvantage/codecommit-sign
    description: "Generate a signed AWS V4 CodeCommit URL directly from an IAM role. No dedicated CodeCommit credentials needed"
    maintainer: Gemba Advantage <github@gembaadvantage.com>
    license: MIT
    vendor: Gemba Advantage
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/codecommit-sign.bash
        dst: /usr/share/bash-completion/completions/codecommit-sign
        file_info:
          mode: 0644
      - src: ./completions/codecommit-sign.fish
        dst: /usr/share/fish/completions/codecommit-sign.fish
        file_info:
          mode: 0644
      - src: ./completions/codecommit-sign.zsh
        dst: /usr/share/zsh/vendor-completions/_codecommit-sign
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/codecommit-sign/copyright
        file_info:
          mode: 0644
      - src: ./manpages/codecommit-sign.1.gz
        dst: /usr/share/man/man1/codecommit-sign.1.gz
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

aurs:
  - homepage: https://github.com/gembaadvantage/codecommit-sign
    description: "Generate a signed AWS V4 CodeCommit URL directly from an IAM role. No dedicated CodeCommit credentials needed"
    maintainers:
      - "Paul T <paul dot t at gembaadvantage dot com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/codecommit-sign-bin.git"
    package: |-
      # bin
      install -Dm755 "./codecommit-sign" "${pkgdir}/usr/bin/codecommit-sign"

      # license
      install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/codecommit-sign/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/codecommit-sign.bash" "${pkgdir}/usr/share/bash-completion/completions/codecommit-sign"
      install -Dm644 "./completions/codecommit-sign.zsh" "${pkgdir}/usr/share/zsh/site-functions/_codecommit-sign"
      install -Dm644 "./completions/codecommit-sign.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/codecommit-sign.fish"

      # manpages
      install -Dm644 "./manpages/codecommit-sign.1.gz" "${pkgdir}/usr/share/man/man1/codecommit-sign.1.gz"
